### PR TITLE
comment out docs link

### PR DESCRIPTION
**Pull request by oxinabox**
Currently there are no docs worth linking to and the deploy key is not setup

### CODE REVIEW

**Comment by iamed2** [comment]
booooo

**Comment by iamed2** [comment]
By default, autodocs is set up which will pull your public docstrings. That's better than nothing. Just set up the deploy key.

**Comment by oxinabox** [comment]
Orly? I did not know that.
Yes ok, will do

**Comment by iamed2** [comment]
Yeah! It's a pretty nice default thingy :)

**Pull request merged**
