### PR TITLE
Functions for getting and setting

### PR DESCRIPTION
**Pull request by grahamas**
Methods for indexing via either an AbstractDict or a NamedTuple.

### CODE REVIEW

**Comment by oxinabox** [comment]
Please tell me more of the motivation for this.

**Comment by grahamas** [comment]
So sorry!  I was in the process of opening an issue to explain but got pulled into a meeting.

> Please tell me more of the motivation for this.
> What's the advantage of this over: `xs[mapping...]` ?

Is that supposed to work? That would honestly be preferable, but I didn't immediately see how to implement it, so I thought I'd start with this. For a Dict you could absolutely just match Vararg of Pairs, but a NamedTuple splats into its values, not into pairs. Using NamedDims#master on Julia v1.5.1:

```
julia> nda = NamedDimsArray{(:x, :y, :z)}(rand(10, 20, 30));

julia> nda[x=3, y=4, z=5]
0.7773934314787121

julia> mapping_correct_order = (x=3,y=4,z=5)
(x = 3, y = 4, z = 5)

julia> nda[mapping_correct_order...]
0.7773934314787121

julia> mapping_wrong_order = (y=4,x=3,z=5)
(y = 4, x = 3, z = 5)

julia> nda[mapping_wrong_order...]
0.43160952031296995

julia> mapping_partial = (y=4,x=3)
(y = 4, x = 3)

julia> nda[mapping_partial...]
ERROR: BoundsError: attempt to access 10×20×30 Array{Float64,3} at index [4, 3]
Stacktrace:
 [1] getindex at ./array.jl:810 [inlined]
 [2] getindex(::NamedDimsArray{(:x, :y, :z),Float64,3,Array{Float64,3}}, ::Int64, ::Int64) at /home/graham/.julia/packages/NamedDims/iHgve/src/wrapper_array.jl:161
 [3] top-level scope at REPL[13]:1

julia> dict_mapping = Dict(:y=>4,:x=>3,:z=>5)
Dict{Symbol,Int64} with 3 entries:
  :y => 4
  :z => 5
  :x => 3

julia> nda[dict_mapping...]
ERROR: ArgumentError: invalid index: :y => 4 of type Pair{Symbol,Int64}
Stacktrace:
 [1] to_index(::Pair{Symbol,Int64}) at ./indices.jl:297
 [2] to_index(::Array{Float64,3}, ::Pair{Symbol,Int64}) at ./indices.jl:274
 [3] to_indices at ./indices.jl:325 [inlined]
 [4] to_indices at ./indices.jl:321 [inlined]
 [5] getindex(::NamedDimsArray{(:x, :y, :z),Float64,3,Array{Float64,3}}, ::Pair{Symbol,Int64}, ::Pair{Symbol,Int64}, ::Pair{Symbol,Int64}) at /home/graham/.julia/packages/NamedDims/iHgve/src/wrapper_array.jl:160
 [6] top-level scope at REPL[18]:1
```

**Comment by mcabbott** [comment]
I guess the hurdle is that `;` inside `[ ]` means `typed_vcat`, not keywords:
```julia
julia> sh(xs...; kw...) = (@show xs kw; nothing);

julia> sh(mapping_partial...) # positional
xs = (4, 3)
kw = Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}()

julia> sh(; mapping_partial...)  # named
xs = ()
kw = Base.Iterators.Pairs(:y => 4,:x => 3)

julia> nda[; mapping_partial...]
ERROR: syntax: unexpected ";"
Stacktrace:
 [1] top-level scope at none:1

julia> sh(()...;mapping_partial...)
xs = ()
kw = Base.Iterators.Pairs(:y => 4,:x => 3)

julia> nda[()...; mapping_partial...]  # still positional, note the type
ERROR: MethodError: no method matching typed_vcat(::NamedDimsArray{(:x, :y, :z),Float64,3,Array{Float64,3}}, ::Int64, ::Int64)
Closest candidates are:
  typed_vcat(::Type{T}, ::Number...) where T at abstractarray.jl:1364
  typed_vcat(::Type, ::Any...) at abstractarray.jl:1636
Stacktrace:
 [1] top-level scope at REPL[62]:1
```

**Comment by grahamas** [comment]
@oxinabox @mcabbott I'm happy to implement an alternate solution if you'd like.  At the moment I'm stuck using my branch because I need to be able to programmatically generate named indices (which I guess is my minimal request here; I'll open an issue to that effect since this is really just a particular solution to that problem).

**Comment by mcabbott** [comment]
You can splat into `getindex` since that takes ordinary keywords, with no strange parsing:
```julia
julia> getindex(nda; mapping_correct_order...)
0.6687728310869365

julia> getindex(nda; mapping_wrong_order...)
0.6687728310869365

julia> getindex(nda; mapping_partial...)
30-element NamedDimsArray(::Vector{Float64}, (:z,)):
↓ :z  0.3707582778145124
      0.5803347465805793
      0.4196182725538635
...

julia> parent(nda)[(3,4,5)]
ERROR: ArgumentError: invalid index: (3, 4, 5) of type Tuple{Int64, Int64, Int64}
Stacktrace:
 [1] to_index(i::Tuple{Int64, Int64, Int64})
   @ Base ./indices.jl:297
```
The slightly weird thing about making a NamedTuple a valid index, without the splat, is that ordinary Tuples aren't. Not sure it's a dealbreaker, but it's slightly odd. Since the names are part of the type, at least `@code_warntype getindex(nda; mapping_partial...)` remains happy. 

Can you explain more what you mean by "programmatically generate named indices"?

**Comment by grahamas** [comment]
> You can splat into `getindex` since that takes ordinary keywords, with no strange parsing:

Huh. For some reason I'd thought this worked with `getindex` and not with `setindex!`, but I just tested it (again?) and  `setindex!` works. I'm perfectly fine with this solution; I don't need the syntactic sugar.  Let me just double check I can translate all my code into this syntax and I'll close this out and put this solution to the issue and close that as well.

**Comment by grahamas** [comment]
Yeah `getindex` and `setindex!` work just fine.  Thanks, @mcabbott !

**Pull request closed without merging**
