### PR TITLE
Extend CovarianceEstimation.cov

### LINKED ISSUE #120: Extend CovarianceEstimation.cov
The current covariance (and correlation) methods overload `Statistics.cov` (`Statistics.cor`).

When using [CovarianceEstimation.jl](https://github.com/mateuszbaran/CovarianceEstimation.jl) another `cov` method is exported that takes a `CovarianceEstimator` type.

The issue is that as of 0.2.4, `cov` returns a `Symmetric` matrix which incorrectly wraps the `NamedDimsArray` if it gets given one.

```julia
julia> using CovarianceEstimation, LinearAlgebra, NamedDims

julia> x = NamedDimsArray{(:a, :b)}(rand(5, 5));

julia> estimator = LinearShrinkage(DiagonalCommonVariance(); corrected=true)

julia> cov(estimator, x)
5×5 Symmetric{Float64,NamedDimsArray{(:b, :b),Float64,2,Array{Float64,2}}}:
  0.0668947  -0.0         0.0         0.0        -0.0
 -0.0         0.0668947  -0.0         0.0         0.0
  0.0        -0.0         0.0668947  -0.0         0.0
  0.0         0.0        -0.0         0.0668947  -0.0
 -0.0         0.0         0.0        -0.0         0.0668947
```

We need to extend the function properly with:
```julia
function CovarianceEstimation.cov(
    estimator::LinearShrinkage, a::NamedDimsArray{L, T, 2};
    dims=1,
) where {L, T}
    numerical_dims = dim(a, dims)
    data = cov(estimator, parent(a); dims=numerical_dims)
    names = symmetric_names(L, numerical_dims)
    return NamedDimsArray{names}(data)
end
```

then we get
```julia
julia> cov(LinearShrinkage(DiagonalCommonVariance(); corrected=true), x)
5×5 NamedDimsArray{(:b, :b),Float64,2,Symmetric{Float64,Array{Float64,2}}}:
  0.0668947  -0.0         0.0         0.0        -0.0
 -0.0         0.0668947  -0.0         0.0         0.0
  0.0        -0.0         0.0668947  -0.0         0.0
  0.0         0.0        -0.0         0.0668947  -0.0
 -0.0         0.0         0.0        -0.0         0.0668947
```

### PR DESCRIPTION
**Pull request by glennmoy**
Closes #120

### CODE REVIEW

**Comment by oxinabox** [comment]
This should be done via REQUIRES.jl, same as we do Tracker.

**Comment by glennmoy** [comment]
> This should be done via REQUIRES.jl, same as we do Tracker.

ah, interesting - thanks!

**Comment by glennmoy** [comment]
I've been getting the following warning but can't seem to figure out why. I'm `using CovarianceEstimation` the same as `Tracker`, which doesn't throw a warning.

```julia
┌ Warning: Package NamedDims does not have CovarianceEstimation in its dependencies:
│ - If you have NamedDims checked out for development and have
│   added CovarianceEstimation as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with NamedDims
└ Loading CovarianceEstimation into NamedDims from project dependency, future warnings for NamedDims are suppressed.
Test Summary: | Pass  Broken  Total
NamedDims.jl  |  896       3    899
    Testing NamedDims tests passed 
```

**Comment by mzgubic** [comment]
I found this:
https://github.com/JuliaPackaging/Requires.jl/issues/52

So you can either add a `.` to `using CovarianceEstimation` to make it `using .CovarianceEstimation`

or delete the line and do
```
for E in (:(CovarianceEstimation.LinearShrinkage),
          :(CovarianceEstimation.SimpleCovariance),
          :(CovarianceEstimation.AnalyticalNonlinearShrinkage))
```

**Comment by rofinn** [comment]
FWIW, I'm not sure I like using Requires.jl for this. If the `cov` api changes at any point then we can't handle that disconnect. That seems particularly likely given that the package is only on 0.2.5.

**Comment by oxinabox** [comment]
OK, I am sold, lets extend it directly for now

**Comment by oxinabox** [comment]
For now let's just add a direct dependency, and change it later.
This is blocking us getting performance enhancements of more recent CovarianceEstimstion releases

**Comment by mzgubic** [comment]
rebased in https://github.com/invenia/NamedDims.jl/pull/174

**Pull request closed without merging**
